# DS 3000/CS 3200 Lab 1

Due: Tuesday May 12 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub as per the instructions in Part 4, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

#### Note:
Future Labs/Homeworks do not need to be submitted via GitHub; I'm only asking you to do it on this Lab to practice with using GitHub (as it will be important to be familiar with its usage for the project). For some of you this is likely already second nature.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

You will use the markdown language in formatting parts of your project. Use it below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a working hyperlink to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.

# Cybersecurity in the EU
  ![Cybersecurity in the EU](https://atlantsecurity.com/images/blog/10-best-eu-cybersecurity-consulting-companies.jpg)

  ## What is Cybersecurity?
    Cybersecurity is the practice of protecting systems, networks, or devices from digital or physical attacks, unauthorized access, or damage.
    Some examples of possible threats cybersecurity must defend against are:
    - Computer Hacking
    - Network Attacks
    - Social Engineering
    - Physical Attacks to Infrasture
  ## Uses in EU
    As the European Union both houses lots of data related to European countries, it is important to keep this data safe and secure from any potential hackers. Additionally, the EU works to inform and advice its countries on how to handle and prevent cyberattacks.
### Pillars of the Global Cybersecurity
    Below is a table that contains the framework on a nation's cybersecurity commitment as according to the International Telecommunication Union, a United Nations specialized agency for information and communication technologies.
| Pillar                  | Explanation                                                                                                                      |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Legal Measures          | Evaluates the existence of legislation, regulations, and legal frameworks related to cybercrime and cybersecurity.               |
| Technical Measures      | Assesses the implementation of technical capabilities, such as national Computer Emergency Response Teams (CERTs) and standards. |
| Organizational Measures | Measures the existence of national strategies, policies, and agencies dedicated to cybersecurity coordination.                   |
| Capacity Development    | Evaluates investments in awareness, education, training programs, and certified professionals.                                   |
| Cooperation             | Measures participation in partnerships, sharing agreements, and international forums to combat cyber threats                     |


Learn more from the [UN Office of Counter-terrorism!](https://www.un.org/counterterrorism/en/cybersecurity)

Equation:
$$ grade = classActivities*0.4 + homework/labs*0.6 $$

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [ ]:
# make sure to import numpy library
import sys
import numpy as np

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting numpy
  Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl (12.6 MB)
Installing collected packages: numpy
Successfully installed numpy-2.4.4
Note: you may need to restart the kernel to use updated packages.

In [13]:
array_a = np.array([[3, 8, -2, 3], [.5, -1, 6, 4], [-5, 7, -42, 2]], dtype=int)
array_b = np.array([[42, 38, 34], [30, 26, 22], [18, 14, 10], [6, 2, -2], [-6, -10, -14]], dtype=int)

In [14]:
# uncomment below to print array_a
array_a

array([[  3,   8,  -2,   3],
       [  0,  -1,   6,   4],
       [ -5,   7, -42,   2]])

In [13]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [ ]:
t_array_a = array_a.T
t_array_b = array_b.T

# np.add(array_a + t_array_b)
# ValueError: operands could not be broadcast together with shapes (3,4) (3,5) 

t_array_b2 = np.delete(t_array_b, 0, -1)
# print(t_array_b2)
added_array = np.add(array_a, t_array_b2)
# print(added_array)

[[ 30  18   6  -6]
 [ 26  14   2 -10]
 [ 22  10  -2 -14]]
[[ 33  26   4  -3]
 [ 26  13   8  -6]
 [ 17  17 -44 -12]]

By adding the two arrays, each cell was added with the cell in the same location on the other array to create a new one

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [26]:
# make sure to import pandas library
import pandas as pd

In [21]:
df = pd.read_csv("train_stations_europe.csv")
df.head()

,id,name,latitude,longitude,parent_station_id,country,time_zone,is_city,is_main_station,is_airport
0,1,Chateau-Arnoux-St-Auban,44.081790,6.001625,NaN,FR,Europe/Paris,True,False,False
1,2,Chateau-Arnoux-St-Auban,44.061565,5.997373,1.0,FR,Europe/Paris,False,True,False
2,3,Chateau-Arnoux Mairie,44.063863,6.011248,1.0,FR,Europe/Paris,False,False,False
3,4,Digne-les-Bains,44.350000,6.350000,NaN,FR,Europe/Paris,True,False,False
4,6,Digne-les-Bains,44.088710,6.222982,4.0,FR,Europe/Paris,False,True,False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [ ]:
subset_df = df[(df["is_city"] == True) & (df["country"] == "BE")]

subset_df.head()
subset_df.describe()

                 id   latitude  longitude  parent_station_id
count     11.000000   9.000000   9.000000                0.0
mean   18741.363636  50.719715   4.810847                NaN
std    12582.067773   0.366820   0.996916                NaN
min     5964.000000  49.999779   3.263740                NaN
25%     5988.500000  50.617431   4.351739                NaN
50%    23044.000000  50.718089   4.444643                NaN
75%    29330.000000  50.979756   5.701847                NaN
max    35397.000000  51.221722   6.120155                NaN

The function .describe() only runs on numerical columns (id, latitude, longitude, and parent_station_id) and excludes all non-numeric columns such as name and time_zone. This means that .describe() only describes numerical column, and looks for basis statistical information such as the distribution, mean, and min and max of the data.

# Part 4: GitHub (10 points)

The below process is obviously not necessary, but designed to give students with minimal Git experience some practice using Git in the command line. When you finish the first three parts of this lab, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer26), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer26 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.
  - **Note**: you only have to do this for this assignment; future assignments can be uploaded directly to Gradescope